language: objective-c
osx_image: xcode10.2

script:
- ./build.sh
- ./test.sh
- mkdir -p Carthage/Build/iOS
- cp -r build/dlib.framework Carthage/Build/iOS/dlib.framework
- zip -r Carthage.framework.zip Carthage

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: s4ukYcbYBm2gjtMbwJbZKm3GcfaU7Hdb3r9KOJvcdRB18IMDj9H8DmVy+v7SrhZwBVo88whLA12w0nTJXgJ5iAtd2/MLaVtujYW4wo2T0aay1Gqc4WAY7b5hnH8aY80u11b8kNd5bi8sgLFVl+hFdh+ockkGNcge4l3M0bchSAW5vvkhC7+NaMHH4lL5aSKfgCfAXiNUtkIWOdJxd8XCnk5BZF7z5kJAv6fhN5dC82gt8/ZzElNEIesMIQQl8pPk7qjg797LIf8zb2X1PI6Gql31GvVtSG9FwHjjkDwoV52ycTwxSyF4mztwE14+BDav0xkN0bQ4uGapXV+feWcUjVhIN5w4UdGM+k1mW5wMsDzjMJxUns215H7mli9dhdNYNIOHfedzrHr+6x+u7g43al3xqlHJRU6zjrNkSw+Sqy/UsLZmBNWFQABIFe9RU3e+PhOrqSU7k+ArJAbvtHJpn5nUePu7PIgx62j12K/MhnIOIwSpcK/kXmQAfbLUn+F1aiKYFliGzM/HGaVogExX0GaYrWFXXrlc0On3E6S4N2spVF9deF0yQUECQGMhMtn5qKbLGdcD+CiuFnfpdiWYRv4DRwniQQrpDUdWX/cAU8MM9dDj6jfjJqG6IAwEfWaI11fd8eweuH8d1eZQA5pUsA9u0MGwinQJ9btsW7CHM8E=
  file: Carthage.framework.zip
  on:
    tags: true
    repo: carlossless/dlib-ios
